<p align="left">
  <a href="https://colab.research.google.com/github/fernandoarcevega/AI_Workshop/blob/main/Part_0/02_Tensors.ipynb" target="_parent">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" width="200">
  </a>
</p>

In [ ]:
###############################################
# Author 1: Wilfrido Gómez-Flores (CINVESTAV) #
# Author 2: Fernando Arce-Vega (CIO)          #
# e-mail 1: wilfrido.gomez@cinvestav.mx       #
# e-mail 2: farce@cio.mx                      #
# Date:     nov/04/2025                       #
# Subject:  Introduction to Tensors           #
###############################################

# `Tensors`
In a computational context, a `tensor` is a `multidimensional array` used to represent, store, and perform operations on data. `Tensors` are fundamental data structures for representing inputs, outputs, weights, and biases in `neural networks`.

`Tensors` are a generalization of:

*   `Scalar (0D tensor)`,
*   `Vector (1D tensor)`,
*   `Matrix (2D tensor)`,
*   `Higher-dimensional tensors (3D, 4D, etc.)`.

## 1. `Tensor attributes`
A `tensor` is defined by three `key attributes`:

*   `Rank`: The number of `axes` or `dimensions`. A `scalar` has `rank` 0, a `vector` has `rank` 1, and a `matrix` has `rank` 2.
*   `Shape`: A `tuple` of integers that specifies the size of the `tensor` along each `axis`. For example, an image `tensor` might have the `shape` `(256, 256, 3)`, representing a `256x256 pixel` image with three color channels.
*   `Data type`: The data type contained in the `tensor`, such as `float32` or `int64`.


## 2. Why use `tensors`?
`Tensors` are crucial for `neural networks` for several reasons:

*   `Data representation`: They enable the efficient representation of complex, `high-dimensional data`, such as images, videos, and text.
*   `Efficient computation`: Modern `deep learning frameworks`, such as `TensorFlow` and `PyTorch`, are based on `tensors`. They are optimized for highly parallel computation on specialized `hardware`, particularly `GPUs` and `TPUs`. The `tensor` structure enables faster training and inference times by performing operations on many data points simultaneously.
*   `Automatic differentiation`: `Tensors` have built-in properties that allow them to track the history of computations. This is essential for `backpropagation`, the process used to train a `neural network` by calculating the `gradients` of the `loss function` with respect to the network parameters (`weights` and `bias`).

## 3. Introduction to `NumPy`
`NumPy` is a fundamental package for scientific computing in `Python`. Among other things, it contains:

*   Powerful `N-dimensional arrays`.
*   Sophisticated `broadcasting` functions.
*   Tools for integrating `C/C++` and `Fortran` code.
*   A large number of linear algebra, `Fourier transform`, and `random` number functions.



### 1. Manual `array` creation

#### 1. Importing `NumPy`
To import the `NumPy` library, use the command `import numpy` and typically import it as `np`.

In [1]:
# Import numpy as np
import numpy as np

#### 2. Manually creating `arrays`
An `array` is created using the reserved word `np.array([])` and can only contain elements of the same type.



In [2]:
# Empty array
array = np.array([])

print(array)
print(type(array))

[]
<class 'numpy.ndarray'>


In [3]:
# 1D array
array_1D = np.array([1, 2, 3, 4.])

print(array_1D)

[1. 2. 3. 4.]


In [4]:
# 2D array
array_2D = np.array([[1, 2, 3, 4, 5],
                       [6, 7, 8, 9, 10]])

print(array_2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# 3D array
array_3D = np.array([[[1, 2, 3],
                        [4, 5, 6]],

                       [[7, 8, 9],
                        [10, 11, 12]]])

print(array_3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### 3. `Array` `data types`
Some `array` data types are:

*   `Integers` (`np.int`),
*   `Floats` (`np.float`),
*   `Complex` (`np.complex`),
*   `Booleans` (`np.bool`),
*   `Objects` (`np.object`),
*   `Strings` (`np.string_`),
*   `Unicode` (`np.unicode_`),
*   Etc.


In [6]:
# Specifying the data type in an array: dtype
array = np.array([1, 2, 3], dtype=np.float64)

print(array)
print(array.dtype)

[1. 2. 3.]
float64


### 2. Automatic `array` creation


#### 1. `Array` of `zeros`
`Numpy` allows you to create `1D`, `2D`, or `ND` `arrays` of zeros using the reserved word `np.zeros`.

In [7]:
# Array of 1D zeros
# Array of 2D zeros
# Array of 3D zeros
zeros = np.zeros((2, 2, 4))
print(zeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


#### 2. `Zero` `arrays like`
`NumPy` allows us to create `arrays` of `zeros` by copying the `shape` of another `array` using the reserved word `np.zeros_like`.

#### 3. `Array` of `ones`
Just like with `arrays` of `zeros`, `NumPy` allows us to create `arrays` of `1D`, `2D`, or `ND` `ones` using the reserved word `np.ones`.

#### 4. `One` `arrays like`
`NumPy` also allows us to create `arrays` of `ones` by copying the `shape` of another `array` using the reserved word `np.ones_like`.

#### 5. `1D` `array` evenly spaced
In `NumPy`, we can create an `array` by specifying the `starting value`, the `ending value`, and the `intervals` between these `values` ​​using the reserved word `np.arange`.

In [8]:
# 1D array evenly spaced: arange
tensor = np.arange(0, 1.2, 0.2)

print(tensor)

[0.  0.2 0.4 0.6 0.8 1. ]


#### 6. `1D` `array` evenly spaced over a given interval
In `NumPy`, we can create an `array` by specifying the `starting value`, the `ending value`, and the `number of divisions` using the `np.linspace` keyword.

In [9]:
# 1D array evenly spaced: linspace
tensor = np.linspace(0, 1, 6)

print(tensor)

[0.  0.2 0.4 0.6 0.8 1. ]


#### 7. `Array` of a `single value`.
It is possible to create an `array` where all its elements have the same `value` using the reserved word `np.full`.


#### 8. `Identity array`
To generate an `identity array`, we use the `np.eye` instruction.

#### 9. `Array` of `empty values`
It is possible to generate `arrays` with empty values ​​using the `empty` command.

#### 10. `Empty array`
`NumPy` also allows us to create `empty arrays` by copying the `shape` of another `array` using the reserved word `np.empty_like`.

#### 11. `Arrays` of `random values`
`NumPy` has subroutines for generating `pseudo-random` numbers from different `statistical distributions`.

In [10]:
# 1D random array (0-1): random.random
# 2D random array: random.random
# 3D random array: random.random
tensor = np.random.random((2, 2, 2))

print(tensor)

[[[0.44654162 0.9846356 ]
  [0.04755341 0.61991941]]

 [[0.47670242 0.44472069]
  [0.53036034 0.7632163 ]]]


#### 8. Sorting `arrays`
The `np.sort` command returns an `array` sorted along a specified `axis`.

#### 9. `Array indexing`
It is possible to access one or more elements of an `array` through `indexing`.

In [11]:
# Indexing a scalar in a 1D array
# Indexing the last element
array = np.arange(100)
array_2D = np.reshape(array, (10, 10))
print(array_2D)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
# Indexing a row
array_2D[2, :]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
# Indexing a column
array_2D[:, 1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [15]:
# Indexing an array
array_2D[4:7, 4:7]

array([[44, 45, 46],
       [54, 55, 56],
       [64, 65, 66]])

#### 10. `Array concatenation`
To join two `arrays`, you can use the `np.concatenate` command. This command enables you to specify the direction of `concatenation`.

In [17]:
# Concatenation of two arrays
array_1 = np.array([[1, 2, 3]])
array_2 = np.array([[4, 5, 6]])
array_3 = np.concatenate([array_1, array_2], axis=1)
print(array_3)

[[1 2 3 4 5 6]]


### 3. `Array` dimensions

#### 1. Number of dimensions in an `array`.
The number of elements in each dimension of an `array` can be determined using the `np.shape` command.

In [18]:
# Number of dimensions in an array: shape
tensor = np.zeros((10, 3, 3))

print(tensor.shape)

(10, 3, 3)


#### 2. Number of `bytes` per element in an `array`
The number of `bytes` per element in an `array` can be determined using the `itemsize` `keyword`.



#### 3. Number of dimensions in an `array` or `Rank`
The number of `dimensions` (or `rank`) in an `array` can be determined using the `ndim` `keyword`.

#### 4. Number of elements in an `array`
To determine the number of elements in an `array`, use the `np.size` `instruction`.

#### 5. `Data type` in an `array`
To determine the data `type` in an `array`, use the `dtype` `instruction`.

#### 6. Changing the `data type` in an `array`
In `NumPy`, you can specify the data type of an `array` using the `astype` `instruction`.

### 4. `Array` manipulation


#### 1. `Resizing` an `Array`
With the `np.reshape` `instruction`, it is possible to `resize` an `array` in `NumPy`.

In [19]:
# Resize an array: reshape
tensor = np.arange(100)
print(tensor)
matrix = np.reshape(tensor, (10, 10))
print(matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### 2. Manipulating `array` values
To manipulate the values ​​in an `array`, it is necessary to first `index` them and then reassign them.

In [21]:
# Manipulating array values
matrix[0, :] = 0
print(matrix)

[[ 0  0  0  0  0  0  0  0  0  0]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### 3. `Copying` an `array`
You can copy an `array` using the `np.copy` `command`.

In [23]:
# Copy of an array: copy
a = np.array([1, 2, 3])
b = np.copy(a)

print(a)
print(b)

[1 2 3]
[1 2 3]


#### 4. Importance of `copying` an `array`
The importance of `copying` an `array` lies in the fact that if we modify the `copied array` or the `assigned array`, the modification affects both.



In [24]:
# Importance of copying from an array: np.copy
a = np.array([1, 2, 3])
b = np.copy(a)
a[0] = 100
print(a)
print(b)

[100   2   3]
[1 2 3]


### 5. Maths with `arrays`

#### 1. `Vectorization`
In `NumPy`, `vectorizing` operations is very simple and convenient.

`But what does vectorization mean in this context?`

`"Vectorization is the art of getting rid of explicit for loops in your code,"` `Andrew Ng said`.

This brings the following advantages:
*   Code savings.
*   More efficient algorithm execution.

In [36]:
# Comparison: Vectorized dot product with
# Non-vectorized dot product
import time
num = 1000000

a = np.random.rand(num).astype(np.float128)
b = np.random.rand(num).astype(np.float128)

# Vectorized operation
tic = time.time()
res_vectorized = np.dot(a, b)
toc = time.time()
time_vectorized = toc - tic

# Non-vectorized
tic = time.time()
res_no_vectorized = 0
for i in range(num):
  res_no_vectorized += + a[i] * b[i]
toc = time.time()
time_no_vectorized = toc - tic

# Printing results
print(f'Vectorized result:     {res_vectorized}')
print(f'Non vectorized result: {res_no_vectorized}')
print(f'Vectorized time:       {time_vectorized}')
print(f'Non vectorized result: {time_no_vectorized}')
print(f'Relationship: {time_no_vectorized/time_vectorized}')

Vectorized result:     250330.70644672995
Non vectorized result: 250330.70644672995
Vectorized time:       0.004082441329956055
Non vectorized result: 0.5398547649383545
Relationship: 132.23821760205573


#### 2. Arithmetic operations
Some of the most common arithmetic operations in `Python` are the following:

*   `Subtract arrays`: `np.subtract`,
*   `Add arrays`: `np.add`.
*   `Multiply arrays`: `np.matmul`,
*   `Multiply arrays`: `np.multiply`,
*   `Multiply arrays`: `np.dot`,
*   `Divide arrays`: `np.divide`,
*   Etc.

#### 3. Inverse of an `array`
It is possible to calculate the inverse of an `array using` the instruction `np.linalg.inv`.

#### 4. `Pseudo-inverse` (`Moore-Penrose`) of an `array`
To calculate the `pseudo-inverse` of an `array`, use `np.linalg.pinv`.

### 6. Aggregation functions
These are the functions that allow us to perform calculations on the same `array`.

#### 1. Sum of elements in an `array`
This allows us to calculate the sum of the elements in different `axes` of the `array` or in the entire `array`.

In [37]:
# Sum of rows and/or columns in an array
matrix = np.array([[1, 2, 3, 5],
                   [0, 3, -1, -4]])

print(np.min(matrix, axis = 1))

[ 1 -4]


#### 2. `Minimums` in an `array`
This allows us to calculate the `minimum element` on different `axes` of the `array` or in the `entire array`.

#### 3. `Maximums` in an `array`
This allows us to calculate the `maximum element` on different `axes` of the `array` or in the `entire array`.


#### 4. `Averages` in an `array`
This allows us to calculate the `average of the elements` on different `axes` of the `array` or in the `entire array`.

#### 5. `Standard deviations` in an `array`
This allows us to calculate the `standard deviation` of the elements on different `axes` of the `array` or in the `entire array`.

#### 6. `Covariance` between `arrays`
This allows us to calculate the `covariance` on a specific `axis` of the `array`.

#### 7. `Correlation coefficient` between `arrays`
This allows us to calculate the `correlatio` between `two arrays`.

#### 8. `Sorting arrays`
The `np.sort` instruction returns an `array sorted` with respect to a specified `axis`.

### 8. `Broadcasting`

#### 1. It's generally not possible to perform arithmetic operations on `arrays` of different `shapes`. However, this can be done with `Python`, `TensorFlow`, and `PyTorch`.

`Broadcasting` is the term used to describe the ability to perform arithmetic operations on arrays of different `shapes`.



#### 2. `Broadcasting` rules
`NumPy` compares the `shapes` of `tensors` from `right-to-left`.

Two `shapes` are compatible if:

*   They are the same, or
*   One of them is 1 (so it can be `stretched` to match the other).

If all dimensions are compatible, `broadcasting` is performed.

Otherwise, an error is generated.

In [38]:
# Broadcasting array - escalar
a = np.array([1, 2, 3])
b = 10

print('Array a: ')
print(a)
print('')

print('Array b: ')
print(b)
print('')

print('La suma de a + b: ')
print(a + b)

Array a: 
[1 2 3]

Array b: 
10

La suma de a + b: 
[11 12 13]


In [39]:
# Broadcasting array - array: (2, 3) (3,)
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

b = np.array([10, 20, 30])  # shape (3,)

print(np.shape(a))
print(np.shape(b))
print()
print(a)
print(b)
print()
print(a + b)

(2, 3)
(3,)

[[1 2 3]
 [4 5 6]]
[10 20 30]

[[11 22 33]
 [14 25 36]]


In [40]:
# Broadcasting array - array (2, 3) (2, 1)
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

b = np.array([[10],
              [20]])        # shape (2, 1)

print(np.shape(a))
print(np.shape(b))
print()
print(a)
print(b)
print()
print(a + b)

(2, 3)
(2, 1)

[[1 2 3]
 [4 5 6]]
[[10]
 [20]]

[[11 12 13]
 [24 25 26]]


In [44]:
# Formas no compatibles de Broadcasting
a = np.ones((2, 3))  # shape (2, 3)
b = np.ones((3, 1))  # shape (3, 1)

# Esto produce un error
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

#### 3. `Broadcasting` compares `shape`s: `right-to-left`.

Because the last `shapes` are incompatible (`2≠3`), broadcasting fails.

`Why is broadcasting important?`
*   `Memory-efficient`: `NumPy` doesn't copy data; it simply reuses it virtually.
*   `Faster`: It avoids explicit `Python loops`.
*   `Readable`: The code is cleaner and more closely resembles mathematical notation.